# Generated by Django 2.2.1 on 2019-09-03 23:38

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Fotoğraf')),
                ('isConfirmed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('1', 'Temel Elektronik'), ('2', 'Elektronik Tasarım'), ('3', 'Endüstriyel Otomasyon'), ('4', 'C Programlama'), ('5', 'FPGA-VHDL'), ('6', 'PIC'), ('0', 'Diğer')], default='0', max_length=60, verbose_name='Kategori')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
    ]
