# Generated by Django 2.2.1 on 2019-09-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Önizleme'),
        ),
    ]
