# Generated by Django 2.2.2 on 2019-09-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190904_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Önizleme(Anasayfada Gözükecek Kısım)'),
        ),
    ]
