# Generated by Django 2.2.2 on 2019-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190904_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Önizleme(Anasayfada Gözükecek Kısım)'),
        ),
    ]
